replace failure by thiserror
ReSpeak/quicklz pull request #2
Opened 2020-05-25 17:57 UTC by ariesdevil

Use `thiserror` as the replacement of `failure` as `failure` is deprecated.

2020-05-25 19:14 UTC, Flakebi requested changes
Thanks, looks good in general. I have a few nitpicks inline.

For future prs, it would be nice to split actual changes from formatting changes, either in different prs or different commits. That makes reviewing a lot easier.

2020-05-25 19:14 UTC, Flakebi commented on src/lib.rs
> +use thiserror::Error as ThisError;
This should be a few lines down with the other uses.
I think you don’t even need to rename it, using it with `#[derive(Error, Debug)]` should work too.

2020-05-25 19:14 UTC, Flakebi commented on src/lib.rs
> +    Io(#[from] ::std::io::Error),
I think you don’t need the leading `::` with the 2018 edition.

2020-05-25 19:14 UTC, Flakebi commented on src/lib.rs
> +pub fn decompress(r: &mut impl Read, max_size: u32) -> Result<Vec<u8>> {
Is there a reason to add the `impl`?
I think this makes the function generic, which means bigger binary sizes and longer compile times.
As long as it doesn’t have a measurable impact on performance, I would like to leave it dynamic.

2020-05-26 03:32 UTC, ariesdevil commented
I'll make a new PR and separate format codes as a new commit

2020-05-26 03:32 UTC, closed without merging